#!/usr/bin/env bash
# Configures localhost to resolve to 127.0.0.2 and facebook.com to 8.8.8.8
grep -v 'localhost' /etc/hosts > /tmp/hosts_new
grep -v 'facebook.com' /tmp/hosts_new > /tmp/hosts_final
echo "127.0.0.2 localhost" >> /tmp/hosts_final
echo "8.8.8.8 facebook.com" >> /tmp/hosts_final
cp /tmp/hosts_final /etc/hosts
